create table if not exists public.portfolio_videos (
    id bigint generated by default as identity primary key,
    category_tag text not null check (category_tag in ('디자인', '3D', '예능')),
    title text not null,
    video_id text,
    url text,
    video_type text default 'YouTube',
    description text,
    thumbnail_url text,
    published_at timestamptz,
    sort_order int not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists portfolio_videos_category_tag_idx on public.portfolio_videos (category_tag);
create index if not exists portfolio_videos_is_active_idx on public.portfolio_videos (is_active);
create index if not exists portfolio_videos_sort_order_idx on public.portfolio_videos (sort_order);

alter table public.portfolio_videos enable row level security;

drop policy if exists "Public read active videos" on public.portfolio_videos;
create policy "Public read active videos"
on public.portfolio_videos
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Authenticated write videos" on public.portfolio_videos;
create policy "Authenticated write videos"
on public.portfolio_videos
for all
to authenticated
using (true)
with check (true);

create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_portfolio_videos_updated_at on public.portfolio_videos;
create trigger trg_portfolio_videos_updated_at
before update on public.portfolio_videos
for each row execute function public.set_updated_at();

